version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - password
    volumes:
      - db-data:/var/lib/postgresql/data
  mysql:
    image: mysql:alpine
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: base

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis

volumes:
  db-data:
    driver: local
  mysql-data:
    driver: local
  redis-data:
    driver: local